databases:
  - name: codelab_backend_db
    plan: free
    databaseName: codelab_backend
    user: codelab_backend

services:
  - type: web
    plan: free
    name: codelab_backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn codelab_backend.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codelab_backend_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4